USE SPRINGBOOT_DEMO;
DROP TABLE IF EXISTS DEPARTMENT;
DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS EMPLOYEE;

--DROP TABLE IF EXISTS DEPARTMENT;
CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID INT IDENTITY(1,1) PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(100),
	CREATED_BY INT,
	CREATED_ON DATETIME,
	MODIFIED_BY INT,
	MODIFIED_ON DATETIME
);

--DROP TABLE IF EXISTS ADDRESS;
CREATE TABLE ADDRESS (
    ADDRESS_ID INT IDENTITY(1,1) PRIMARY KEY,
    ADDRESS_LINE1 VARCHAR(50),
	ADDRESS_LINE2 VARCHAR(50),
	CITY VARCHAR(50),
	STATE VARCHAR(50),
	COUNTRY VARCHAR(50),
	ZIP_CODE INT,
	CREATED_BY INT,
	CREATED_ON DATETIME,
	MODIFIED_BY INT,
	MODIFIED_ON DATETIME
);

--DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID INT IDENTITY(1,1) PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR(255),
    AGE INT,
    SALARY NUMERIC(10,2),
	DEPARTMENT_ID INT,
	ADDRESS_ID INT,
	CREATED_BY INT,
	CREATED_ON DATETIME,
	MODIFIED_BY INT,
	MODIFIED_ON DATETIME,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID),
	FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID)
);